-- ==========================================================
-- UNAIB COMPUTER ACCESSORIES - PostgreSQL Schema (Supabase)
-- Embedded POS, Inventory, Purchases, Warranty & Ledgers
-- ==========================================================

-- 1. User Access Control (RBAC)
CREATE TABLE IF NOT EXISTS users (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    username TEXT UNIQUE NOT NULL,
    password_hash TEXT NOT NULL,
    pin TEXT,
    full_name TEXT NOT NULL,
    role TEXT NOT NULL CHECK(role IN ('admin', 'cashier')),
    phone TEXT,
    is_active INTEGER DEFAULT 1,
    created_at TIMESTAMPTZ DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMPTZ DEFAULT CURRENT_TIMESTAMP
);

-- 2. Product Categories
CREATE TABLE IF NOT EXISTS categories (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name TEXT UNIQUE NOT NULL,
    description TEXT,
    created_at TIMESTAMPTZ DEFAULT CURRENT_TIMESTAMP
);

-- 3. Suppliers (Vendors / Distributors)
CREATE TABLE IF NOT EXISTS suppliers (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name TEXT NOT NULL,
    contact_person TEXT,
    phone TEXT,
    email TEXT,
    address TEXT,
    current_balance NUMERIC(12, 2) DEFAULT 0.0,
    total_due NUMERIC(12, 2) DEFAULT 0.0,
    created_at TIMESTAMPTZ DEFAULT CURRENT_TIMESTAMP
);

-- 4. Inventory Products
CREATE TABLE IF NOT EXISTS products (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    barcode TEXT UNIQUE,
    name TEXT NOT NULL,
    category_id BIGINT REFERENCES categories(id) ON DELETE SET NULL,
    cost_price NUMERIC(12, 2) NOT NULL DEFAULT 0.0,
    sale_price NUMERIC(12, 2) NOT NULL DEFAULT 0.0,
    stock_quantity INTEGER NOT NULL DEFAULT 0,
    low_stock_threshold INTEGER NOT NULL DEFAULT 5,
    supplier_id BIGINT REFERENCES suppliers(id) ON DELETE SET NULL,
    has_serials INTEGER DEFAULT 0,
    warranty_months INTEGER DEFAULT 12,
    description TEXT,
    created_at TIMESTAMPTZ DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMPTZ DEFAULT CURRENT_TIMESTAMP
);

-- 5. Customers
CREATE TABLE IF NOT EXISTS customers (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name TEXT NOT NULL,
    phone TEXT,
    email TEXT,
    address TEXT,
    total_spent NUMERIC(12, 2) DEFAULT 0.0,
    current_balance NUMERIC(12, 2) DEFAULT 0.0,
    created_at TIMESTAMPTZ DEFAULT CURRENT_TIMESTAMP
);

-- 6. Invoices (Sales Orders)
CREATE TABLE IF NOT EXISTS invoices (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    invoice_number TEXT UNIQUE NOT NULL,
    customer_id BIGINT REFERENCES customers(id) ON DELETE SET NULL,
    customer_name TEXT,
    customer_phone TEXT,
    cashier_id BIGINT REFERENCES users(id) ON DELETE SET NULL,
    subtotal NUMERIC(12, 2) NOT NULL DEFAULT 0.0,
    discount_type TEXT DEFAULT 'amount',
    discount_value NUMERIC(12, 2) DEFAULT 0.0,
    discount_amount NUMERIC(12, 2) DEFAULT 0.0,
    tax_rate NUMERIC(12, 2) DEFAULT 0.0,
    tax_amount NUMERIC(12, 2) DEFAULT 0.0,
    grand_total NUMERIC(12, 2) NOT NULL DEFAULT 0.0,
    paid_amount NUMERIC(12, 2) NOT NULL DEFAULT 0.0,
    change_amount NUMERIC(12, 2) DEFAULT 0.0,
    balance_due NUMERIC(12, 2) DEFAULT 0.0,
    payment_method TEXT NOT NULL DEFAULT 'cash',
    status TEXT DEFAULT 'completed',
    previous_customer_balance NUMERIC(12, 2) DEFAULT 0.0,
    new_customer_balance NUMERIC(12, 2) DEFAULT 0.0,
    show_previous_balance INTEGER DEFAULT 1,
    shipping_cost NUMERIC(12, 2) DEFAULT 0.0,
    shipping_notes TEXT,
    extra_charges NUMERIC(12, 2) DEFAULT 0.0,
    notes TEXT,
    void_reason TEXT,
    voided_at TIMESTAMPTZ,
    voided_by BIGINT REFERENCES users(id),
    created_at TIMESTAMPTZ DEFAULT CURRENT_TIMESTAMP
);

-- 7. Invoice Line Items
CREATE TABLE IF NOT EXISTS invoice_items (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    invoice_id BIGINT NOT NULL REFERENCES invoices(id) ON DELETE CASCADE,
    product_id BIGINT REFERENCES products(id) ON DELETE SET NULL,
    product_name TEXT NOT NULL,
    cost_price NUMERIC(12, 2) NOT NULL DEFAULT 0.0,
    unit_price NUMERIC(12, 2) NOT NULL DEFAULT 0.0,
    quantity INTEGER NOT NULL DEFAULT 1,
    total_price NUMERIC(12, 2) NOT NULL DEFAULT 0.0,
    warranty_months INTEGER DEFAULT 0
);

-- 8. Purchases (Stock Inward / Vendor Orders)
CREATE TABLE IF NOT EXISTS purchases (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    purchase_number TEXT UNIQUE NOT NULL,
    supplier_id BIGINT NOT NULL REFERENCES suppliers(id) ON DELETE CASCADE,
    supplier_invoice_no TEXT,
    purchase_date DATE NOT NULL,
    subtotal NUMERIC(12, 2) NOT NULL DEFAULT 0.0,
    discount NUMERIC(12, 2) DEFAULT 0.0,
    tax_rate NUMERIC(12, 2) DEFAULT 0.0,
    tax_amount NUMERIC(12, 2) DEFAULT 0.0,
    grand_total NUMERIC(12, 2) NOT NULL DEFAULT 0.0,
    paid_amount NUMERIC(12, 2) NOT NULL DEFAULT 0.0,
    balance_due NUMERIC(12, 2) DEFAULT 0.0,
    previous_supplier_balance NUMERIC(12, 2) DEFAULT 0.0,
    new_supplier_balance NUMERIC(12, 2) DEFAULT 0.0,
    payment_method TEXT DEFAULT 'cash',
    status TEXT DEFAULT 'completed',
    void_reason TEXT,
    voided_at TIMESTAMPTZ,
    voided_by BIGINT REFERENCES users(id),
    notes TEXT,
    created_at TIMESTAMPTZ DEFAULT CURRENT_TIMESTAMP
);

-- 9. Purchase Line Items
CREATE TABLE IF NOT EXISTS purchase_items (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    purchase_id BIGINT NOT NULL REFERENCES purchases(id) ON DELETE CASCADE,
    product_id BIGINT REFERENCES products(id) ON DELETE SET NULL,
    product_name TEXT NOT NULL,
    cost_price NUMERIC(12, 2) NOT NULL DEFAULT 0.0,
    sale_price NUMERIC(12, 2) NOT NULL DEFAULT 0.0,
    quantity INTEGER NOT NULL DEFAULT 1,
    total_cost NUMERIC(12, 2) NOT NULL DEFAULT 0.0
);

-- 10. Financial Accounts (Cash Drawer, Bank Accounts, Wallets)
CREATE TABLE IF NOT EXISTS accounts (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name TEXT NOT NULL,
    type TEXT NOT NULL CHECK(type IN ('cash', 'bank', 'wallet')),
    account_number TEXT,
    branch_name TEXT,
    current_balance NUMERIC(12, 2) NOT NULL DEFAULT 0.0,
    is_default INTEGER DEFAULT 0,
    created_at TIMESTAMPTZ DEFAULT CURRENT_TIMESTAMP
);

-- 10b. Financial Accounts Ledger (Cash Counter & Bank Inflows/Outflows)
CREATE TABLE IF NOT EXISTS accounts_ledger (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    account_id BIGINT REFERENCES accounts(id) ON DELETE CASCADE,
    entry_type VARCHAR(50) NOT NULL,
    reference_no VARCHAR(100),
    debit NUMERIC(12, 2) DEFAULT 0.0,
    credit NUMERIC(12, 2) DEFAULT 0.0,
    balance_after NUMERIC(12, 2) DEFAULT 0.0,
    description TEXT,
    created_at TIMESTAMPTZ DEFAULT CURRENT_TIMESTAMP
);
CREATE INDEX IF NOT EXISTS idx_accounts_ledger_account ON accounts_ledger(account_id);

-- 11. Unified Party Ledgers (Khata for Supplier & Client)
CREATE TABLE IF NOT EXISTS ledger_entries (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    party_type TEXT NOT NULL CHECK(party_type IN ('supplier', 'client', 'customer')),
    party_id BIGINT NOT NULL,
    entry_type TEXT NOT NULL,
    reference_id BIGINT,
    reference_no TEXT,
    debit NUMERIC(12, 2) NOT NULL DEFAULT 0.0,
    credit NUMERIC(12, 2) NOT NULL DEFAULT 0.0,
    account_id BIGINT REFERENCES accounts(id) ON DELETE SET NULL,
    description TEXT,
    entry_date DATE NOT NULL,
    created_at TIMESTAMPTZ DEFAULT CURRENT_TIMESTAMP
);

-- 12. Serial Numbers & Warranty Records
CREATE TABLE IF NOT EXISTS serial_numbers (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    serial_number TEXT UNIQUE NOT NULL,
    product_id BIGINT NOT NULL REFERENCES products(id) ON DELETE CASCADE,
    purchase_id BIGINT REFERENCES purchases(id) ON DELETE SET NULL,
    purchase_item_id BIGINT REFERENCES purchase_items(id) ON DELETE SET NULL,
    status TEXT DEFAULT 'in_stock',
    invoice_id BIGINT REFERENCES invoices(id) ON DELETE SET NULL,
    invoice_item_id BIGINT REFERENCES invoice_items(id) ON DELETE SET NULL,
    customer_id BIGINT REFERENCES customers(id) ON DELETE SET NULL,
    sold_date TIMESTAMPTZ,
    warranty_expiry_date TIMESTAMPTZ,
    vendor_warranty_expiry TIMESTAMPTZ,
    notes TEXT,
    created_at TIMESTAMPTZ DEFAULT CURRENT_TIMESTAMP
);

-- 13. Warranty Claims & RMA Tracking
CREATE TABLE IF NOT EXISTS warranty_claims (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    claim_number TEXT UNIQUE NOT NULL,
    serial_number_id BIGINT NOT NULL REFERENCES serial_numbers(id) ON DELETE CASCADE,
    invoice_id BIGINT REFERENCES invoices(id) ON DELETE SET NULL,
    customer_id BIGINT REFERENCES customers(id) ON DELETE SET NULL,
    issue_description TEXT NOT NULL,
    status TEXT DEFAULT 'pending',
    resolution_notes TEXT,
    created_at TIMESTAMPTZ DEFAULT CURRENT_TIMESTAMP,
    resolved_at TIMESTAMPTZ
);

-- 14. Operational Expenses
CREATE TABLE IF NOT EXISTS expenses (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    user_id BIGINT REFERENCES users(id) ON DELETE SET NULL,
    category TEXT NOT NULL,
    amount NUMERIC(12, 2) NOT NULL,
    payment_method TEXT DEFAULT 'cash',
    description TEXT,
    expense_date DATE NOT NULL,
    created_at TIMESTAMPTZ DEFAULT CURRENT_TIMESTAMP
);

-- 15. Cash Drawer Shifts & Reconciliation
CREATE TABLE IF NOT EXISTS cash_drawers (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    cashier_id BIGINT NOT NULL REFERENCES users(id) ON DELETE CASCADE,
    opened_at TIMESTAMPTZ DEFAULT CURRENT_TIMESTAMP,
    closed_at TIMESTAMPTZ,
    opening_cash NUMERIC(12, 2) NOT NULL DEFAULT 0.0,
    cash_sales NUMERIC(12, 2) DEFAULT 0.0,
    cash_expenses NUMERIC(12, 2) DEFAULT 0.0,
    expected_closing_cash NUMERIC(12, 2) DEFAULT 0.0,
    actual_closing_cash NUMERIC(12, 2),
    discrepancy NUMERIC(12, 2),
    status TEXT DEFAULT 'open',
    notes TEXT
);

-- 16. Store Settings
CREATE TABLE IF NOT EXISTS store_settings (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    key TEXT UNIQUE NOT NULL,
    value TEXT NOT NULL
);

-- 17. Sales Returns (سیل واپسی)
CREATE TABLE IF NOT EXISTS sales_returns (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    return_number TEXT UNIQUE NOT NULL,
    invoice_id BIGINT REFERENCES invoices(id) ON DELETE SET NULL,
    invoice_number TEXT,
    customer_id BIGINT REFERENCES customers(id) ON DELETE SET NULL,
    customer_name TEXT,
    customer_phone TEXT,
    refund_mode TEXT NOT NULL DEFAULT 'cash',
    total_refund_amount NUMERIC(12, 2) NOT NULL DEFAULT 0.0,
    reason TEXT,
    cashier_id BIGINT REFERENCES users(id) ON DELETE SET NULL,
    created_at TIMESTAMPTZ DEFAULT CURRENT_TIMESTAMP
);

-- 18. Sales Return Items
CREATE TABLE IF NOT EXISTS sales_return_items (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    sales_return_id BIGINT NOT NULL REFERENCES sales_returns(id) ON DELETE CASCADE,
    product_id BIGINT NOT NULL REFERENCES products(id),
    product_name TEXT NOT NULL,
    quantity INTEGER NOT NULL DEFAULT 1,
    unit_price NUMERIC(12, 2) NOT NULL,
    total_amount NUMERIC(12, 2) NOT NULL,
    serial_numbers TEXT
);

-- 19. Purchase Returns (خریداری واپسی / سپلائر کو مال واپسی)
CREATE TABLE IF NOT EXISTS purchase_returns (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    return_number TEXT UNIQUE NOT NULL,
    purchase_id BIGINT REFERENCES purchases(id) ON DELETE SET NULL,
    purchase_number TEXT,
    supplier_id BIGINT NOT NULL REFERENCES suppliers(id) ON DELETE CASCADE,
    supplier_name TEXT,
    total_amount NUMERIC(12, 2) NOT NULL DEFAULT 0.0,
    refund_mode TEXT NOT NULL DEFAULT 'deduct_balance',
    reason TEXT,
    cashier_id BIGINT REFERENCES users(id) ON DELETE SET NULL,
    created_at TIMESTAMPTZ DEFAULT CURRENT_TIMESTAMP
);

-- 20. Purchase Return Items
CREATE TABLE IF NOT EXISTS purchase_return_items (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    purchase_return_id BIGINT NOT NULL REFERENCES purchase_returns(id) ON DELETE CASCADE,
    product_id BIGINT NOT NULL REFERENCES products(id),
    product_name TEXT NOT NULL,
    quantity INTEGER NOT NULL DEFAULT 1,
    unit_cost NUMERIC(12, 2) NOT NULL,
    total_amount NUMERIC(12, 2) NOT NULL
);

-- 21. Stock Alerts
CREATE TABLE IF NOT EXISTS stock_alerts (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    product_id BIGINT NOT NULL REFERENCES products(id),
    product_name TEXT NOT NULL,
    invoice_id BIGINT REFERENCES invoices(id) ON DELETE SET NULL,
    invoice_number TEXT,
    available_before NUMERIC(12, 2) DEFAULT 0.0,
    quantity_sold NUMERIC(12, 2) NOT NULL DEFAULT 1,
    quantity_oversold NUMERIC(12, 2) DEFAULT 0.0,
    status TEXT NOT NULL DEFAULT 'pending',
    notes TEXT,
    created_at TIMESTAMPTZ DEFAULT CURRENT_TIMESTAMP,
    resolved_at TIMESTAMPTZ,
    resolved_by BIGINT REFERENCES users(id)
);

-- 22. Goods Received Note (GRN Header)
CREATE TABLE IF NOT EXISTS grn (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    grn_number TEXT UNIQUE NOT NULL,
    supplier_id BIGINT NOT NULL REFERENCES suppliers(id) ON DELETE RESTRICT,
    total_amount NUMERIC(12, 2) NOT NULL DEFAULT 0.0,
    payment_type TEXT NOT NULL CHECK(payment_type IN ('cash', 'credit')),
    status TEXT NOT NULL DEFAULT 'completed' CHECK(status IN ('completed', 'pending', 'cancelled')),
    received_date DATE NOT NULL,
    notes TEXT,
    created_at TIMESTAMPTZ DEFAULT CURRENT_TIMESTAMP
);

-- 23. GRN Items
CREATE TABLE IF NOT EXISTS grn_items (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    grn_id BIGINT NOT NULL REFERENCES grn(id) ON DELETE CASCADE,
    product_id BIGINT NOT NULL REFERENCES products(id) ON DELETE RESTRICT,
    quantity_ordered INTEGER NOT NULL DEFAULT 1,
    quantity_received INTEGER NOT NULL DEFAULT 1,
    unit_cost NUMERIC(12, 2) NOT NULL DEFAULT 0.0,
    total_cost NUMERIC(12, 2) NOT NULL DEFAULT 0.0
);

-- 24. General Financial Transactions
CREATE TABLE IF NOT EXISTS transactions (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    type TEXT NOT NULL CHECK(type IN ('debit', 'credit')),
    category TEXT NOT NULL,
    amount NUMERIC(12, 2) NOT NULL,
    reference_id BIGINT,
    reference_type TEXT,
    description TEXT,
    created_at TIMESTAMPTZ DEFAULT CURRENT_TIMESTAMP
);

-- Indexes for high-speed indexing
CREATE INDEX IF NOT EXISTS idx_products_barcode ON products(barcode);
CREATE INDEX IF NOT EXISTS idx_products_name ON products(name);
CREATE INDEX IF NOT EXISTS idx_serial_numbers_sn ON serial_numbers(serial_number);
CREATE INDEX IF NOT EXISTS idx_invoices_num ON invoices(invoice_number);
CREATE INDEX IF NOT EXISTS idx_purchases_num ON purchases(purchase_number);
CREATE INDEX IF NOT EXISTS idx_ledger_party ON ledger_entries(party_type, party_id);
CREATE INDEX IF NOT EXISTS idx_sales_returns_num ON sales_returns(return_number);
CREATE INDEX IF NOT EXISTS idx_purchase_returns_num ON purchase_returns(return_number);
CREATE INDEX IF NOT EXISTS idx_stock_alerts_status ON stock_alerts(status);
CREATE INDEX IF NOT EXISTS idx_grn_number ON grn(grn_number);
CREATE INDEX IF NOT EXISTS idx_grn_supplier ON grn(supplier_id);
CREATE INDEX IF NOT EXISTS idx_grn_items_grn_id ON grn_items(grn_id);
CREATE INDEX IF NOT EXISTS idx_transactions_cat ON transactions(category);

-- Default Seeds
INSERT INTO users (id, username, password_hash, pin, full_name, role, phone)
VALUES 
(1, 'admin', '8c6976e5b5410415bde908bd4dee15dfb167a9c873fc4bb8a81f6f2ab448a918', '1234', 'Unaib Store Admin', 'admin', '03001234567'),
(2, 'cashier', '8c6976e5b5410415bde908bd4dee15dfb167a9c873fc4bb8a81f6f2ab448a918', '0000', 'Counter Cashier', 'cashier', '03007654321')
ON CONFLICT (id) DO NOTHING;

INSERT INTO accounts (id, name, type, account_number, is_default)
VALUES (1, 'Main Cash Drawer', 'cash', NULL, 1)
ON CONFLICT (id) DO NOTHING;

INSERT INTO store_settings (key, value)
VALUES 
('store_name', 'Unaib Computer Accessories'),
('store_tagline', 'Your Trusted Hardware & Accessories Hub'),
('store_phone', '0300-1234567'),
('store_address', 'Shop #12, Computer Plaza, Hafeez Centre, Lahore'),
('store_footer', 'Warranty claims require original receipt. Thank you for your business!')
ON CONFLICT (key) DO NOTHING;
